### ISSUE TITLE
IAutofacAuthenticationFilter (HttpContext == null)

### ISSUE THREAD

**Issue by Xorcist77** [autofac/Autofac.WebApi#14]
Attempting to access HttpContext.Current in a standard IAuthenticationFilter (WebAPI2 / .NET 4.6) will return the appropriate HttpContext object.

However using Autofac.WebAPI2 3.4.0, and attempting to access HttpContext.Current in an injected IAutofacAuthenticationFilter will result in null.

**Comment by Xorcist77** [comment]
Please note this causes issues with other libraries that expect a valid HttpContext to be present.

Specifically in my case, NHibernate, using a per-request unit of work, and setup early in an OWIN pipeline so that the current session is available throughout the lifetime of the request. ISessionFactory.GetCurrentSession returns null, because the HttpContext that is used to store the session is null, while within IAutofacAuthenticationFilter.

Also note that IAutofacActionFilter **does not** appear to have the same issue. Accessing HttpContext within a IAutofacActionFilter works 100%.

**Comment by tillig** [comment]
Do you happen to have a simple repro we can use to debug in and see what's going on?

Note that we're currently pretty consumed trying to get .NET Core support going. If you are able to debug into it and see what might be happening to help us solve it, we could get a fix out sooner.

I know when I run into issues like this, the things I look at are:

- Is the thing trying to access `HttpContext.Current` registered as a singleton? Singletons, depending on where they're used, may get resolved before the filter runs.
- Is the error happening outside a request? For example, sometimes at app startup certain logic runs and there really is no context.
- If I debug into the problem area and look at `HttpContext.Current` can I see it?
- Is there something asynchronous going on where the call context may have been lost? For example, a call in a synchronous method to an asynchronous method?

I'm not saying any of these are definitely the issue, just throwing out the things I look at first. If you can pinpoint where it's happening (we do have symbols on SymbolSource) we'll be better able to get a fix in if possible.

**Comment by tillig** [comment]
For reference, it appears the question has also been posted [to StackOverflow](http://stackoverflow.com/questions/37732779/owin-nhibernate-webapi-iautofacauthenticationfilter-no-httpcontext).

**Comment by Xorcist77** [comment]
Oh yeah, that's actually me.

I asked that question originally on StackOverflow before I came here. After doing a bit of research and determining that the standard webapi filters worked just fine (and that the IAutofacActionFilter worked but


 the IAutofacAuthenticationFilter didn't) , I figured I better go straight to the source.

I have attached a sample VS2015 project here. You can change whether the standard webapi filters are used or autofac filters are injected via a web.config "InjectFilters" appSetting.


[HttpContext_Issue.zip](http://www.maxeta.net/HttpContext_Issue.zip)

**Comment by Xorcist77** [comment]
Any updates on this? Were you able to reference my sample project? It's pretty clear that the standard Microsoft filters all have access the HttpContext, and so does AutoFac's IAutofacActionFilter. So by virtue of maintaining consistency the IAutofacAuthenticationFilter should also... but it currently does not.

**Comment by tillig** [comment]
Sorry, no progress. Please believe when I have the time to look into this and troubleshoot it, I will, and this issue will be updated. You haven't been forgotten. Until then, a looooot of time is being spent trying to account for the .NET Core RTM that happened a couple of days ago, getting all of the packages updated. That's what most of our time in the last several months have been prioritized toward.

If you need an answer quicker than that, unfortunately the best I can recommend is for you to pull down the code and build it/step into it to see what's going on. You may also configure SymbolSource as a symbol server - I think we have the symbols/source posted out there so you may be able to step in that way.

**Comment by kimiolek** [comment]
The problem occurs not only in IAutofacAuthenticationFilter. In my case, null refrence exception was throw when setup autofac with owin and nhibernate and call ISessionFactory.GetCurrentSession. 

The solution was:
1. Install OwinRequestScopeContext package (PM> Install-Package OwinRequestScopeContext)
2. Add OwinSessionContext class like:
```
[Serializable]
    public class OwinSessionContext : MapBasedSessionContext
    {
        private const string SessionFactoryMapKey = "NHibernate.Context.WebSessionContext.SessionFactoryMapKey";

        public OwinSessionContext(ISessionFactoryImplementor factory) : base(factory) { }

        protected override IDictionary GetMap()
        {
            if (!OwinRequestScopeContext.Current.Items.ContainsKey(SessionFactoryMapKey))
                return null;

            return OwinRequestScopeContext.Current.Items[SessionFactoryMapKey] as IDictionary;
        }

        protected override void SetMap(IDictionary value)
        {
            OwinRequestScopeContext.Current.Items[SessionFactoryMapKey] = value;
        }
    }

```
3. Configure nhibernate to use OwinSessionContext by passing:

`config.SetProperty("current_session_context_class", "NHContext.Models.OwinSessionContext, NHContext");`

or 
`<property name="current_session_context_class">NHContext.Models.OwinSessionContext, NHContext</property>`

**Comment by Grassycup** [comment]
Hello, I looked at the source code, and it seems like 
`return Task.Run(() => OnAuthenticate(context), cancellationToken);`
 from [AuthenticationFilterWrapper.cs](https://github.com/autofac/Autofac.WebApi/blob/7a49de1c8ab3251f364c356e34db4924133542f8/src/Autofac.Integration.WebApi/AuthenticationFilterWrapper.cs), method `IAuthenticationFilter.AuthenticateAsync` was causing that issue.

If I did my homework correctly, Task.Run starts a background task which is not associated with a `HttpContext.Current`. I was able to make Xorcist77's example work by running `OnAuthenticate ` synchronously, and just returning a null task.

```
[SecurityCritical]
Task IAuthenticationFilter.AuthenticateAsync(HttpAuthenticationContext context, CancellationToken cancellationToken)
{
    OnAuthenticate(context);
    return Task.FromResult<object>(null);
}
```
I wasn't sure if doing this will cause performance issues, or not being able to use `CancellationToken `would cause problems anywhere else. But this does seem to fix the issue.

**Comment by tillig** [comment]
Excellent find! Given we also want to fix #6 and get async working better all the way through, it sounds like a short term solution might be to fix that up, but longer term switching to use all Task-based interfaces if possible would help avoid these issues in the future.

**Comment by tillig** [comment]
I just pushed Autofac.WebApi2 4.0.0-CI-220 to MyGet (`https://www.myget.org/F/autofac/api/v3/index.json`) which includes the switch of the filter interfaces to use the Task/async instead of synchronous versions. That should also fix this.

Anyone interested in trying it out and letting me know if it works?

**Comment by Xorcist77** [comment]
I updated my sample using the myget release you specified, then updated the filters, and things appear to be working... I have access to the HttpContext in both IAutofacActionFilter and IAutofacAuthenticationFilter filters now. I'll do some further "real world" testing and let you know if I run into any issues. I assume this is a prospective fix for the next stable build headed to nuget.

**Comment by tillig** [comment]
Absolutely. If it appears to prove out, I'll push it to the next 4.0 beta on NuGet.

**Comment by tillig** [comment]
I went ahead and pushed [4.0.0-rc3-225 to NuGet](https://www.nuget.org/packages/Autofac.WebApi2/4.0.0-rc3-225) with these changes and a few other fixes that have been piling up. I'm going to close the issue with that; if it turns out this _isn't_ actually fixed, let me know and we can re-open.
