### ISSUE TITLE
Breaking Changes in 4.0.0?

### ISSUE THREAD

**Issue by NovakSavicOPAL** [autofac/Autofac.WebApi#15]
Hi. Are there any breaking changes in you 4.0.0 (autofac, autofac.owin, autofac.webapi2, autofac.webapi2.owin) releases in comparison to 3.4.0?

Regards
Novak

**Comment by tillig** [comment]
Yep. [Release notes here.](https://github.com/autofac/Autofac/wiki/Web-Api-Integration-Release-Notes)
