### ISSUE TITLE
Filters provided via dependency injection are called in the same order pre- & post-action

### ISSUE THREAD

**Issue by richarddbarnett** [autofac/Autofac.WebApi#16]
If 2 filters A & B are provided for a controller via depedency injection & `OnActionExecuting` is called for filter A & then filter B, then `OnActionExecuted` is called for A & then B.

If the same filters are added to `HttpConfiguration.Filters` then `OnActionExecuted` is called for B & then A, which I think is the correct order.

* [3.5.2 `ActionFilterWrapper.OnActionExecuting()`](https://github.com/autofac/Autofac/blob/v3.5.2/Core/Source/Autofac.Integration.WebApi/ActionFilterWrapper.cs#L86)
* [3.5.2 `ActionFilterWrapper.OnActionExecuted()`](https://github.com/autofac/Autofac/blob/v3.5.2/Core/Source/Autofac.Integration.WebApi/ActionFilterWrapper.cs#L109)

Observed using Autofac 3.5.2, Autofac.WebApi2 3.4.0.

**Comment by richarddbarnett** [comment]
This also affects [the 4.x branch](https://github.com/autofac/Autofac.WebApi/blob/develop/src/Autofac.Integration.WebApi/ActionFilterWrapper.cs).

**Comment by tillig** [comment]
Verified. We need to run that in the reverse order on action executed. Great catch! Thanks!

**Comment by tillig** [comment]
This is fixed in v4.0.2-CI-234 [on the MyGet feed](https://www.myget.org/F/autofac/api/v3/index.json) and will be available in the next push to NuGet.
