### ISSUE TITLE
Registering one filter type for multiple controllers doesn't work in one statement

### ISSUE THREAD

**Issue by petermorlion** [autofac/Autofac.WebApi#17]
When registering filters, you can't register one type for multiple controllers like this:

```
builder.RegisterType<CustomActionFilter>()
            .AsWebApiActionFilterFor<ProductsController>()
            .AsWebApiActionFilterFor<OrdersController>()
            .InstancePerRequest();
```

Rather, you'll have to do it per controller separately:

```
builder.RegisterType<CustomActionFilter>()
            .AsWebApiActionFilterFor<ProductsController>()
            .InstancePerRequest();

builder.RegisterType<CustomActionFilter>()
            .AsWebApiActionFilterFor<OrdersController>()
            .InstancePerRequest();
```

This can become cumbersome, because often, you'd want to use certain filters for lots, if not all, controllers.

You can't use the first option, because you get an exception stating that an item with the same key has already been added to the dictionary. The key is [`AutofacWebApiFilterProvider.ActionFilterMetadataKey`](https://github.com/autofac/Autofac.WebApi/blob/099883aacbc3cd26af88229581a689e6c447244e/src/Autofac.Integration.WebApi/AutofacWebApiFilterProvider.cs#L54) and has a value of "AutofacWebApiActionFilter".

The problem is that in the [`AsFilterFor`](https://github.com/autofac/Autofac.WebApi/blob/099883aacbc3cd26af88229581a689e6c447244e/src/Autofac.Integration.WebApi/RegistrationExtensions.cs#L543) method, [metadata is constructed](https://github.com/autofac/Autofac.WebApi/blob/099883aacbc3cd26af88229581a689e6c447244e/src/Autofac.Integration.WebApi/RegistrationExtensions.cs#L558) that will be unique in the registration (because of a different controller type), but won't be added with a unique metadatakey (always "AutofacWebApiActionFilter").

I'd be happy to fix this and submit a PR, if you're willing to guide me where and how (and if) you'd like it fixed. Can I safely change the metadatakey to be something unique?

**Comment by tillig** [comment]
Sorry for the delay in getting back to you on this. It's a good find and we'd love to have a PR for it with associated unit tests.

As you've noticed, the way we figure out the way a service is a filter is [by looking at the specific metadata key](https://github.com/autofac/Autofac/blob/v3.5.2/Core/Source/Autofac.Integration.WebApi/AutofacWebApiFilterProvider.cs#L304). If you're able to fix things up so all the filters (action filters, authentication filters, etc.) all work correctly then we'd love a PR for it. I anticipate changing the metadata key may be painful, but I haven't dived in too deep on this.

Anyway, yeah, if you can figure it out, we'd love to see a fix. Thanks!

**Comment by petermorlion** [comment]
I'll have a look into this, but give me some time, because I currently worked around it with a method like this:

```
private void RegisterControllerWithFilters<TController>(ContainerBuilder builder) where TController : IHttpController
{
    builder.RegisterType<TController>().InstancePerRequest();

    builder.RegisterType<MyExceptionFilter>()
        .AsWebApiExceptionFilterFor<TController>()
        .InstancePerRequest();

    builder.RegisterType<MyAuthorizationFilter>()
        .AsWebApiAuthorizationFilterFor<TController>()
        .InstancePerRequest();
}
```

And then calling it like this:

    RegisterControllerWithFilters<MyController>(builder);
