### ISSUE TITLE
AsWebApiAuthorizationFilterOverrideFor does not overrride

### ISSUE THREAD

**Issue by medokin** [autofac/Autofac.WebApi#25]
Here ist my default Authorizations filter:

```c#
builder.RegisterType<IsLoggedInAuthorizationFilter>()
  .AsWebApiAuthorizationFilterFor<BroadcastsController>()
  .InstancePerRequest();
```

This works fine, but if I want to overrride the Filter to allow anonymous requests like this:

```c#
builder.RegisterType<AnonymousAuthorizationFilter>()
  .AsWebApiAuthorizationFilterOverrideFor<BroadcastsController>()
  .InstancePerRequest();
```

Both get called:
1. AnonymousAuthorizationFilter
2. IsLoggedInAuthorizationFilter

I would expect that only `AnonymousAuthorizationFilter` gets called.

Is that the intended behavior, or am I'm doing something wrong?

There is literally no documentions for AsWebApiAuthorizationFilterOverrideFor and I cannot find anything on the web.

**Comment by tillig** [comment]
Sorry about the lack of docs; we'll try to address that soon.

In the meantime, a good place to look in any open source project when there aren't docs is the source. Knowing that Web API filters come from filter providers, [looking at `AutofacWebApiFilterProvider.GetFilters`](https://github.com/autofac/Autofac.WebApi/blob/099883aacbc3cd26af88229581a689e6c447244e/src/Autofac.Integration.WebApi/AutofacWebApiFilterProvider.cs#L83) shows that what you are seeing is the correct behavior.

Short story: The point of the override filter call is more to ensure the override filters are returned _before_ other filters. However, the number of override filters registered is not limited, so you may have multiple override filters and all of them will be returned.

**Comment by tillig** [comment]
[New docs](http://autofac.readthedocs.io/en/latest/integration/webapi.html#filter-overrides) and [an extensive, descriptive unit test](https://github.com/autofac/Autofac.WebApi/blob/d202d01ae384ae77b38f21c8645b92f5d902f4cc/test/Autofac.Integration.WebApi.Test/FilterOrderingFixture.cs) to help you on your way.

**Comment by medokin** [comment]
@tillig Thanks for the explanation and your Hyperspeed docs additions.
