### ISSUE TITLE
AutofacWebApiModelBinderProvider doesn't work

### ISSUE THREAD

**Issue by ilyabreev** [autofac/Autofac.WebApi#26]
Model and binder:
```
    public class MyModel
    {
        public int Number { get; set; }
    }

    public class MyModelBinder : IModelBinder
    {
        public bool BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
        {
            return true;
        }
    }
```

web api configuration
```
var builder = new ContainerBuilder();
// Register your Web API controllers.
builder.RegisterApiControllers(Assembly.GetExecutingAssembly());
builder.RegisterWebApiModelBinderProvider();
builder.RegisterType<MyModelBinder>().AsModelBinderForTypes(typeof(MyModel));
var container = builder.Build();
config.DependencyResolver = new AutofacWebApiDependencyResolver(container);
```

web api method
```
        public void Post(MyModel model)
        {
        }
```

So `BindModel` method is never called.
Am I doing something wrong?

**Comment by tillig** [comment]
Have you tried asking your question on StackOverflow [or searching for answers like this one](http://stackoverflow.com/questions/21195150/autofac-model-binding-provider-in-web-api-2)? How-to questions will have more eyes on them and get quicker responses on SO than they will if they're just issues.

**Comment by ilyabreev** [comment]
All answers are the same. They mention obsolete methods or solutions that
not work for me. So... here we go :-)
пт, 7 апр. 2017 г. в 20:50, Travis Illig <notifications@github.com>:

**Comment by tillig** [comment]
Looking at your example, I'm guessing it's because you didn't mark the `MyModel` parameter with `[ModelBinder]`.

[Per the Web API documentation:](https://docs.microsoft.com/en-us/aspnet/web-api/overview/formats-and-model-binding/parameter-binding-in-aspnet-web-api)

> With a model-binding provider, you still need to add the `[ModelBinder]` attribute to the parameter, to tell Web API that it should use a model binder and not a media-type formatter. But now you don't need to specify the type of model binder in the attribute.

I'm going to update the documentation in the Web API integration section of the Autofac doc to include info on that.
