### ISSUE TITLE
Suggestion: Alternative solution for injecting HttpRequestMessage

### ISSUE THREAD

**Issue by rexcfnghk** [autofac/Autofac.WebApi#28]
The current implementation of injecting `HttpRequestMessage` relies on updating the component registry

```c#
internal static void UpdateScopeWithHttpRequestMessage(HttpRequestMessage request)
{
    var scope = request.GetDependencyScope();
    var requestScope = scope.GetRequestLifetimeScope();
     if (requestScope == null) return;

     var registry = requestScope.ComponentRegistry;
     var builder = new ContainerBuilder();
     builder.Register(c => request).InstancePerRequest();
     builder.Update(registry);
}
```

https://github.com/autofac/Autofac.WebApi/blob/develop/src/Autofac.Integration.WebApi/CurrentRequestHandler.cs#L66

However this defeats the best practices in the documentation: the [container should be considered immutable](http://docs.autofac.org/en/latest/best-practices/#consider-a-container-as-immutable).

Also `ContainerBuilder.Update` is marked as obsolete in this commit https://github.com/autofac/Autofac/commit/8a89e94ad2ffed0c10ac613b7015c11a56275c99

Should another approach be considered? Like the one Simple Injector is using, by capturing the `HttpRequestMessage` in a provider:
https://github.com/simpleinjector/SimpleInjector/blob/master/src/SimpleInjector.Integration.WebApi/SimpleInjectorWebApiExtensions.cs

I will be happy to help with a pull request if needed.

**Comment by alexmg** [comment]
The container update certainly isn't ideal. I'm definitely open to a PR if you would like to put something together.

**Comment by rexcfnghk** [comment]
If I create a PR that simply adapts to Simple Injector's way of injecting `HttpRequestMessage`, will it create any licensing issues?

**Comment by tillig** [comment]
Both projects are MIT license, so there's no problem. It appears SimpleInjector is using the same mechanism as the ASP.NET Core `HttpContextAccessor` anyway, so that's not a new pattern.

**Comment by rexcfnghk** [comment]
I see. I will come up with a PR soon!
