### ISSUE TITLE
Help - Autofac.WebApi2 Global Action FIlters Parameters injection failed

### ISSUE THREAD

**Issue by flarocca** [autofac/Autofac.WebApi#35]
Hi all,

I'm facing an issue with some global ActionFilters where I'm expecting to get injected a dependency that is not happening.

It is probably because I'm missing something, but I can find what.
[Here](https://stackoverflow.com/questions/50634363/autofac-webapi2-global-action-filters-injection-failed?noredirect=1#comment88279449_50634363) is the StackOverflow question I posted.
Do you guys want me to include all the description here as well?

Thanks.

**Comment by tillig** [comment]
No need to double post, we follow SO already so if we have an answer or time to research, we'll catch you there.
