### ISSUE TITLE
Please, consider to release the 4.2.0 version of the Nuget package

### ISSUE THREAD

**Issue by micros-uz** [autofac/Autofac.WebApi#36]
Hello guys, thank you for this very useful library. We would like to use the new version since it has very important feature - GetService/GetServices methods are virtual. 

We were able to deal without this feature by creating a new implementation of IDependencyResolver and aggregating an instance of AutofacWebApiDependencyResolver but today we have faced with the following: RegisterWebApiFilterProvider we wanted to use today seriously relies on the fact that HttpConfiguration.DependencyResolver is a subclass of AutofacWebApiDependencyResolver (please, see DependencyResolverExtensions.GetRootLifetimeScope) so our custom implementation of IDependencyResolver does not work for RegisterWebApiFilterProvider. 

In case that methods are virtual we no longer need in aggregating AutofacWebApiDependencyResolver and will just inherit from it in order to override virtual methods. And that check in DependencyResolverExtensions.GetRootLifetimeScope will not break.

**Comment by tillig** [comment]
Done.
- https://www.nuget.org/packages/Autofac.WebApi2/4.2.0
- https://github.com/autofac/Autofac.WebApi/releases/tag/v4.2.0

**Comment by micros-uz** [comment]
Thank you very much!
