### ISSUE TITLE
Could not load file or assembly 'Autofac, Version=3.0.0.0' when using Autofac.WebApi 3.1.0

### ISSUE THREAD

**Issue by shashikantn** [autofac/Autofac.WebApi#37]
When i am using 

 id="Autofac" version="4.6.1" targetFramework="net462" />
 id="Autofac.WebApi" version="3.1.0" targetFramework="net462" />
 id="Steeltoe.CloudFoundry.ConnectorAutofac" version="2.0.0" targetFramework="net462" />

in VS2017, with .net framework 4.6.2, getting below error in runtime,
**Could not load file or assembly 'Autofac, Version=3.0.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)**

**Comment by tillig** [comment]
Add a binding redirect to Autofac 4.6.1 into your web.config. Usually NuGet does this for you. Apparently this didn't happen for you.

**Comment by shashikantn** [comment]
@tillig thanks for the reply.
Yes, i have added that in web.config, but still facing the issue. 
But, when i remove Autofac.WebApi reference, it works fine.
Have you come across such issue?

**Comment by shashikantn** [comment]
resolved it by using Autofac.webApi2. Thanks
