### ISSUE TITLE
Performance: Use TryGetValue instead of ContainsKey() + indexer sequence

### ISSUE THREAD

**Issue by dnickless** [autofac/Autofac.WebApi#40]
No biggie but this should really use Dictionary.TryGetValue for performance reasons:

https://github.com/autofac/Autofac.WebApi/blob/e10c3faf87db8de741d43d3ba5aaba9e20fed2d6/src/Autofac.Integration.WebApi/ActionFilterWrapper.cs#L126-L127

![image](https://user-images.githubusercontent.com/985774/54918081-9e3cfc00-4efd-11e9-98fb-1b14afbb7754.png)

Admittedly, the profiler session was using the "Tracing" configuration so we should expect an overemphasis on small methods but then again, this change should be a safe no-brainer.

**Comment by tillig** [comment]
I feel like we looked at something similar to this in another area. Possibly not WebAPI integration, but a place where we were using Contains instead of TryGetValue. I'd have to do the benchmarks again, but I'm vaguely recalling that for _small_ collections, Contains was actually faster; for _larger_ collections, TryGetValue won out.

Hmmm. Let me whip up a benchmark to see if I'm remembering right.

**Comment by tillig** [comment]
Well, either I'm not remembering correctly or something has changed, at least in .NET Core. It appears `TryGet` is slightly faster than `Contains` + `Item` in all cases by a few nanoseconds. We'll have to look at updating. (Pull requests welcome.)

My benchmarks looked at small and large collections, for three different keys that existed in the collections and one that didn't.

Benchmark results:

|                 Method |     KeyToFind |Mean |     Error |    StdDev |   Median |
|----------------------- |---------:|---------:|----------:|----------:|---------:|
| Large_ContainsNotFound | |16.59 ns | 0.1507 ns | 0.1336 ns | 16.60 ns |
|   Large_TryGetNotFound | |16.02 ns | 0.3521 ns | 0.3294 ns | 15.90 ns |
| Small_ContainsNotFound | |20.72 ns | 0.5514 ns | 1.5370 ns | 20.23 ns |
|   Small_TryGetNotFound | |17.86 ns | 0.5261 ns | 0.4664 ns | 17.75 ns |
| Large_ContainsFound |              0 | 52.34 ns | 1.1404 ns | 2.3552 ns | 51.84 ns |
|   Large_TryGetFound |              0 | 28.77 ns | 0.6834 ns | 1.6763 ns | 28.35 ns |
| Large_ContainsFound |            500 | 49.87 ns | 1.0940 ns | 2.8043 ns | 49.26 ns |
|   Large_TryGetFound |            500 | 28.73 ns | 0.6493 ns | 0.7730 ns | 28.79 ns |
| Large_ContainsFound |            999 | 52.20 ns | 1.8601 ns | 5.1544 ns | 50.58 ns |
|   Large_TryGetFound |            999 | 27.80 ns | 0.2502 ns | 0.2218 ns | 27.85 ns |
| Small_ContainsFound |              0 | 32.07 ns | 0.2080 ns | 0.1843 ns | 32.06 ns |
|   Small_TryGetFound |              0 | 20.17 ns | 0.5478 ns | 1.1190 ns | 19.86 ns |
| Small_ContainsFound |              5 | 36.43 ns | 1.0781 ns | 3.0933 ns | 36.05 ns |
|   Small_TryGetFound |              5 | 35.68 ns | 2.9433 ns | 8.4921 ns | 35.30 ns |
| Small_ContainsFound |              9 | 59.32 ns | 3.2588 ns | 9.1380 ns | 58.53 ns |
|   Small_TryGetFound |              9 | 28.43 ns | 1.0534 ns | 2.9883 ns | 27.18 ns |

Benchmarks:

```c#
using System;
using System.Collections.Generic;
using BenchmarkDotNet.Attributes;

namespace AutofacSandbox
{
    public class ItemNotFound
    {
        private readonly Dictionary<string, string> _largeData = new Dictionary<string, string>();

        private readonly Dictionary<string, string> _smallData = new Dictionary<string, string>();

        public ItemNotFound()
        {
            for (var i = 0; i < 10; i++)
            {
                this._smallData.Add(i.ToString(), i.ToString());
            }

            for (var i = 0; i < 1000; i++)
            {
                this._largeData.Add(i.ToString(), i.ToString());
            }
        }

        // Comparison is based on the Autofac.WebApi logic:
        // var metadata = filter.Metadata.ContainsKey(this.MetadataKey) ? filter.Metadata[this.MetadataKey] as FilterMetadata : null;
        [Benchmark]
        public string Large_ContainsNotFound() => this._largeData.ContainsKey("not-available") ? this._largeData["not-available"] : null;

        [Benchmark]
        public string Large_TryGetNotFound() => this._largeData.TryGetValue("not-available", out var value) ? value : null;

        [Benchmark]
        public string Small_ContainsNotFound() => this._smallData.ContainsKey("not-available") ? this._smallData["not-available"] : null;

        [Benchmark]
        public string Small_TryGetNotFound() => this._smallData.TryGetValue("not-available", out var value) ? value : null;
    }

    public class SmallCollectionFound
    {
        private readonly Dictionary<string, string> _smallData = new Dictionary<string, string>();

        public SmallCollectionFound()
        {
            for (var i = 0; i < 10; i++)
            {
                this._smallData.Add(i.ToString(), i.ToString());
            }
        }

        // Keys that exist are at the beginning, middle, and end of the logical order
        // though that's not necessarily how they're stored internally.
        [Params("0", "5", "9")]
        public string SmallKeyToFind { get; set; }

        // Comparison is based on the Autofac.WebApi logic:
        // var metadata = filter.Metadata.ContainsKey(this.MetadataKey) ? filter.Metadata[this.MetadataKey] as FilterMetadata : null;
        [Benchmark]
        public string Small_ContainsFound() => this._smallData.ContainsKey(this.SmallKeyToFind) ? this._smallData[this.SmallKeyToFind] : null;

        [Benchmark]
        public string Small_TryGetFound() => this._smallData.TryGetValue(this.SmallKeyToFind, out var value) ? value : null;
    }

    public class LargeCollectionFound
    {
        private readonly Dictionary<string, string> _largeData = new Dictionary<string, string>();

        public LargeCollectionFound()
        {
            for (var i = 0; i < 1000; i++)
            {
                this._largeData.Add(i.ToString(), i.ToString());
            }
        }

        // Keys that exist are at the beginning, middle, and end of the logical order
        // though that's not necessarily how they're stored internally.
        [Params("0", "500", "999")]
        public string LargeKeyToFind { get; set; }

        // Comparison is based on the Autofac.WebApi logic:
        // var metadata = filter.Metadata.ContainsKey(this.MetadataKey) ? filter.Metadata[this.MetadataKey] as FilterMetadata : null;
        [Benchmark]
        public string Large_ContainsFound() => this._largeData.ContainsKey(this.LargeKeyToFind) ? this._largeData[this.LargeKeyToFind] : null;

        [Benchmark]
        public string Large_TryGetFound() => this._largeData.TryGetValue(this.LargeKeyToFind, out var value) ? value : null;
    }
}

```

**Comment by dnickless** [comment]
Perfect, I'll happily create a PR as soon as I can. Mind you, you must remember something else here since with Dictionaries, the reading cost that you generally incur and try to avoid are hashing and equality operations of which you get about twice as many when using `Contains` + `indexer` compared to `TryGetValue`.
