### ISSUE TITLE
async for IAutofacAuthenticationFilter ?

### ISSUE THREAD

**Issue by superlogical** [autofac/Autofac.WebApi#5]
Is there any way to use `void OnAuthenticate(HttpAuthenticationContext context)` with async?

**Comment by tillig** [comment]
Duplicate with #6 
(Sorry - I hadn't moved that one over here since we split the repos.)

**Comment by superlogical** [comment]
I ended up just using Web Apis `DependencyResolver` and grabbing the stuff I need out of it which works okay.. leaving this here in case anyone else want's to solve it this way.

````csharp
public async Task AuthenticateAsync(HttpAuthenticationContext context, CancellationToken cancellationToken)
{
    HttpConfiguration config = context.ActionContext.ControllerContext.Configuration;

    ILifetimeScope scope = config.DependencyResolver.GetRootLifetimeScope();
    IDbConnectionFactory db = scope.Resolve<IDbConnectionFactory>();
    IStore store = scope.Resolve<IStore>();
    
	// Blah Blah Blah   
}
````
