### ISSUE TITLE
Autofac 5 was pushed to Github a few days ago along with MVC 5 but the current version of WebApi2 is not usable with it

### ISSUE THREAD

**Issue by mtaylorfsmb** [autofac/Autofac.WebApi#52]
Cannot upgrade to Autofac 5 until this package is updated to support it.

**Comment by alistairjevans** [comment]
As noted in the Autofac 5 release notes (https://github.com/autofac/Autofac/releases/tag/v5.0.0), we're still working on updating the integration and extension libraries.

Please be patient, we're getting there.

Thanks!
