### ISSUE TITLE
Web requests never return when using Autofac, unless pre-resolved

### ISSUE THREAD

**Issue by jws305** [autofac/Autofac.WebApi#57]
## Describe the Bug

I am having an issue resolving services when using this package.  My services all resolve correctly, except through the controllers registered with Autofac.  When I make a web request, the request never responds and I get no error messages or exceptions being thrown.  I *AM* able to get everything working if I manually request the service right after building the container in the application start method.

## Steps to Reproduce

```c#
public class Global : HttpApplication
{
    private void Application_Start(object sender, EventArgs e)
    {
        var builder = new ContainerBuilder();
        builder.RegisterType<MyService>().As<IMyService>();
        builder.RegisterApiControllers(typeof(WebApiConfig).Assembly).InstancePerRequest();
        IContainer container = builder.Build();

        // When this is uncommented, everything works fine
        //var svc = container.Resolve<IMyService>();

        GlobalConfiguration.Configuration.DependencyResolver = new AutofacWebApiDependencyResolver(ContainerProvider.ApplicationContainer);
    }
}
```
## Expected Behavior

I should either have my service resolved properly, or have an exception thrown.

## Exception with Stack Trace

Unfortunately hard to debug without an exception.

## Dependency Versions

Autofac: v5.2.0
Autofac.Web: v5.0.0
Autofac.WebApi2: v5.0.0

## Additional Info

I simplified the dependencies for sake of example but the full dependency hierarchy looks something like this:

- MyController (InstancePerRequest)
  - IMyService (InstancePerDependency)
    - ISubService (SingleInstance)

**Comment by tillig** [comment]
It looks like there's a problem with the repo, in that there's not enough code here to actually see all the workings.

I see this (trimming the comments)

```c#
IContainer container = builder.Build();
GlobalConfiguration.Configuration.DependencyResolver = new AutofacWebApiDependencyResolver(ContainerProvider.ApplicationContainer);
```

...but I don't see where `ContainerProvider.ApplicationContainer` is being set so there's something being trimmed out or over-simplified.

Is this a typo?

Can you provide more info, like whether you're using OWIN?

It seems you're _also_ using `Autofac.Web` which is for web forms but there's no mention of this being a combination web forms + Web API app. If it's combo, you probably need to use the same container and not try to keep two separate containers based on the stack (web forms vs Web API).

**Comment by jws305** [comment]
Apologies, I found the issue somewhere else.  I did leave a lot of the setup code from the example above.

My issue was that I was calling an async function from a synchronous context during the initialization of services using `var res = GetAsync().Result;`.  This worked fine when I resolved the singleton service eagerly but failed when in the context of an http request.
